export const SEQUELIZE_PROVIDERS_KEYS = {
  SEQUELIZE: 'SEQUELIZE',
  USERS_REPOSITORY: 'USERS_REPOSITORY',
  VINYLS_REPOSITORY: 'VINYLS_REPOSITORY',
  REVIEWS_REPOSITORY: 'REVIEWS_REPOSITORY',
  ROLES_REPOSITORY: 'ROLES_REPOSITORY',
  PURCHASES_REPOSITORY: 'PURCHASES_REPOSITORY',
  LOGS_REPOSITORY: 'LOGS_REPOSITORY',
};
